Repository habx/graphcurl, pull requests merged in 2022-10, with the labels that each got.

#46 APP-32622: fix(docker): Removing meaningless COPYs
  Dockerfile
Labels: automerge, automerge-delayed-1day

#44 APP-32606: feat(docker): replace base img scratch by alpine
  Dockerfile
Labels: automerge, squash, autorelease

#48 APP-32666: [SKIP CI] Releasing v0.4.0
  .codecov.yml
Labels: automerge, squash
